language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
      - uo236851@uniovi.es
    on_success: never
    on_failure: always
    
services:
  - mysql
  
before_install:
    - pip install --upgrade pip
    - pip install codecov
    - mysql -u root -e 'create database Usuarios;'
    - mysql -u root -e 'Use Usuarios;CREATE TABLE TUSERS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,NIF VARCHAR(255),CODIGOMESA INTEGER NOT NULL,CONTRASEÑA VARCHAR(255),EMAIL VARCHAR(255),NAME VARCHAR(255))'
    
   
after_success:
  - codecov

sudo: required
