language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
      - uo236851@uniovi.es
    on_success: never
    on_failure: always
    
services:
  - mysql

before_script:
    - "./travis-ci-setup -h127.0.0.1 -utravis"
    - make

sudo: required
